# Generated by Django 5.0 on 2024-01-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_hcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='Content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.hcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='Summary',
            field=models.TextField(null=True),
        ),
    ]
